#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
name: "mosquitto"
namespace: "mosquitto"
hostpath: ""

metallb_address_pool: ""
server_ip: ""
load_balancer_ips: ""

logins:
  - username: ""
    password: ""