#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: #@ data.values.name
  name: adlists.list
  namespace: #@ data.values.namespace
data:
  adlists.list:  #@ data.read("/lists/adlists.list")