#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:assert", "assert")
---
apiVersion: v1
data:
  password: #@ base64.encode(data.values.webpassword)
kind: Secret
metadata:
  labels:
    app: #@ data.values.name
  name: pihole-webpassword
  namespace: #@ data.values.namespace
type: Opaque