#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: #@ data.values.name
  name: whitelist.txt
  namespace: #@ data.values.namespace
data:
  whitelist.txt: #@ data.read("/lists/whitelist.txt")