#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: #@ data.values.namespace
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
      name: home-assistant
    spec:
      containers:
        - image: ghcr.io/home-assistant/home-assistant:stable
          imagePullPolicy: Always
          name: home-assistant
          volumeMounts:
            - mountPath: /config
              name: home-assistant-volume
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: America/New_York
      hostNetwork: true
      volumes:
        - hostPath:
            path: #@ data.values.hostpath
          name: home-assistant-volume
